---
services:
  traefik:
    # Tested with docker.io/library/traefik:v3.7.10
    # Note: when upgrading between different Traefik minor versions, see
    # https://doc.traefik.io/traefik/migrate/v3/
    image: docker.io/library/traefik:v3.7
    restart: always
    depends_on: [foo, bar]
    ports: ["80:80"]
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro

  foo:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: foo

  bar:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: bar
