---
# Enable the Traefik API (api@internal service)
api: {}

# Enable access logging to stdout
accessLog: { addInternals: true }

providers:
  # Use the dynamic.yml file as dynamic configuration provider
  file: { directory: /etc/traefik/dynamic }
