---
# Enable the Traefik API (api@internal service)
api: {}

# Enable access logging to stdout
accessLog: { format: json, addInternals: true }

log: { format: json, level: INFO }

providers:
  # Use the dynamic.yml file as dynamic configuration provider
  file: { directory: /etc/traefik/dynamic }
