---
# To test locally, you can use the following approach:
#   ln mkdocs.yml /some/other/dir/mkdocs.yml
#   MKDOCS_DOCS_DST="$PWD" /tmp/venv01/bin/python3 -mmkdocs serve -csf/some/other/dir/mkdocs.yml

strict: true
docs_dir: !ENV MKDOCS_DOCS_DST
site_dir: !ENV MKDOCS_SITE_DIR

# Inspired by https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

site_name: dmotte/misc
site_url: https://dmotte.github.io/misc/
site_author: dmotte
site_description: dmotte/misc

repo_name: dmotte/misc
repo_url: https://github.com/dmotte/misc
edit_uri: blob/main

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips
    - navigation.tabs
    - navigation.indexes # Provides same behavior as the "mkdocs-section-index" plugin
    - navigation.expand
    - navigation.footer
    - navigation.top
    - search.share
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  # favicon: null
  icon: { logo: material/shield }

plugins:
  - minify: { minify_html: true }
  - search

extra:
  consent:
    title: Cookie consent
    description: >-
      This is a static website, but it may still use some cookies. By
      continuing to use this website, you consent to the use of cookies.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dmotte

markdown_extensions:
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      auto_title: true
      auto_title_map: { Text Only: "" }
      linenums: true
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
