---
services:
  haproxy:
    image: docker.io/library/haproxy:2.6
    restart: always
    depends_on: [webserver01, webserver02]
    ports: ["8080:80"]
    volumes: [./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro]

  webserver01:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: webserver01

  webserver02:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: webserver02
