---
# Enable the Traefik API (api@internal service)
api: {}

# Enable access logging to stdout
accessLog: { addInternals: true }

providers:
  # Use the dynamic.yml file as dynamic configuration provider
  file: { directory: /etc/traefik/dynamic }
  # Use Docker (container labels) as dynamic configuration provider
  docker:
    exposedByDefault: false

entryPoints:
  web:
    address: ":80"
  dashboard:
    address: ":8080"
