#!/bin/bash

set -e

show_help() {
    echo "Usage:"
    echo "    $0 [-m message] [-p]"
    echo "    $0 -h|--help"
    echo "Options:"
    echo "    -m, --message    Specify a custom commit message (only used if" \
        "a commit is actually performed)"
    echo "    -p, --pull-only  Do a git pull only instead of a full sync"
    echo "Examples:"
    echo "    $0"
    echo "    $0 --message=\"Hello world!\""
    echo "    $0 -m \"Hello world!\""
    echo "    $0 -m=thisismymessage -p"
}

message="$(date)"

# Parse the argument list
while [ $# -gt 0 ]; do
    case "$1" in
        -m|--message) # This is an "--arg value"-like option
            shift # Past the key to get the value
            message="$1"
            ;;
        -m=*|--message=*) # This is an "--arg=value"-like option
            # No need to shift here since the value is part of the same string
            message="${1#*=}"
            ;;
        -p|--pull-only) # This is an "--arg"-like option
            pull_only="true"
            ;;
        -h|--help) # This is an "--arg"-like option
            show_help
            exit 0
            ;;
        *)
            echo "Unknown option \"$1\""
            show_help
            exit 1
            ;;
    esac

    shift # to get the next option
done

# Pull without letting the user edit any merge commit message
echo "1: Pull from the remote"
git pull --no-edit

[ "$pull_only" = "true" ] && exit 0

echo "2: Add any changes to stage"
git add .
echo "3: Make a commit if needed"
git commit -m "$message" || true
echo "4: Push to the remote"
git push
