---
services:
  prometheus:
    image: docker.io/prom/prometheus:v2.46.0
    restart: always
    ports: ["9090:9090"]
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: docker.io/grafana/grafana-oss:10.1.1
    restart: always
    ports: ["3000:3000"]
    volumes:
      - data-grafana:/var/lib/grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    entrypoint:
      - /bin/sh
      - -ec
      # Note: not using install's "-T" flag as it's not supported in Alpine
      - |
        install -Dm644 /dev/stdin \
          /etc/grafana/provisioning/datasources/prometheus.yml << 'EOF'
        ---
        apiVersion: 1
        datasources:
          - { name: Prometheus, type: prometheus, url: http://prometheus:9090/ }
        EOF
        /run.sh

volumes:
  data-grafana: {}
