# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "mybox"
    config.vm.box_url = "file://../mybox/mybox.json"
    
    config.vm.hostname = "myvm"

    config.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 4
    end

    config.vm.provision "shell", inline: <<-SHELL
        timedatectl set-timezone Europe/Rome
    SHELL

    config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
end
