---
services:
  portmap-client:
    image: docker.io/dmotte/portmap-client:latest
    restart: always
    volumes:
      - ./portmap-client/known_hosts:/known_hosts:ro
      - ./portmap-client/ssh-client-key.pem:/ssh_client_key:ro
    command: portmap@myserver.example.com -NvR8001:traefik:80

  traefik:
    image: docker.io/library/traefik:v3.0
    restart: always
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic/dynamic.yml:ro

  webauthn-proxy:
    image: docker.io/quiq/webauthn_proxy:0.1
    restart: always
    volumes:
      - ./webauthn-proxy-config:/opt/config:ro
      - ./webauthn-proxy-static/authenticated.html:/opt/static/authenticated.html:ro
      - ./webauthn-proxy-static/login.html:/opt/static/login.html:ro
      - ./webauthn-proxy-static/redirect-login.html:/opt/static/redirect-login.html:ro
      - ./webauthn-proxy-static/register.html:/opt/static/register.html:ro
      - ./webauthn-proxy-static/styles.css:/opt/static/styles.css:ro
      - ./webauthn-proxy-static/title-image.png:/opt/static/title-image.png:ro

  whoami:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: whoami

  webserver:
    image: docker.io/joseluisq/static-web-server:2
    restart: always
    volumes: [./webserver-public:/public:ro]
