---
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
    restart: always
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: ":4180"

      OAUTH2_PROXY_COOKIE_EXPIRE: 24h
      OAUTH2_PROXY_COOKIE_SECRET: <put-cookie-secret-here>

      OAUTH2_PROXY_PROVIDER: google
      OAUTH2_PROXY_CLIENT_ID: <put-client-id-here>
      OAUTH2_PROXY_CLIENT_SECRET: <put-client-secret-here>
      OAUTH2_PROXY_REDIRECT_URL: http://localhost:4180/oauth2/callback
      # OAUTH2_PROXY_REDIRECT_URL: https://mydomain.example.com/oauth2/callback
      OAUTH2_PROXY_EMAIL_DOMAINS: "*"

      OAUTH2_PROXY_UPSTREAMS: "http://webserver01/"
      # OAUTH2_PROXY_UPSTREAMS: "file:///var/www/static/#/static/"
      # OAUTH2_PROXY_UPSTREAMS: "static://202"

      # Only set this if you are behind a reverse proxy, i.e. you want OAuth2
      # Proxy to trust the X-Real-IP and X-Forwarded-* headers
      # OAUTH2_PROXY_REVERSE_PROXY: "true"

      OAUTH2_PROXY_CUSTOM_SIGN_IN_LOGO: "https://training.play-with-docker.com/images/docker-logo.svg"
      OAUTH2_PROXY_BANNER: >
        My banner <b>text</b> (just below the logo)
      OAUTH2_PROXY_FOOTER: >
        My footer text. Like the banner, it supports <i>HTML</i> formatting
      # If you want to skip the sign-in page entirely and directly reach the
      # next step
      # OAUTH2_PROXY_SKIP_PROVIDER_BUTTON: "true"
    ports: ["4180:4180"]
    depends_on: [webserver01]

  webserver01:
    image: docker.io/traefik/whoami:v1.10
    restart: always
    hostname: webserver01
