---
name: main

on:
  push: # All branches and tags

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  job:
    permissions: { id-token: write, pages: write }
    uses: dmotte/misc/.github/workflows/cicd-with-script.yml@main
    with:
      script: |
        export MISC_SCRIPTS_DIR="$GITHUB_ACTION_PATH/../../scripts"
        find . -type f \( -name 'cicd.sh' -o -name 'cicd-*.sh' \) |
          while read -r i; do
            echo "########## RUNNING $i"; bash "$i"; echo
          done
